import argparse
import json

import httpx

APP_NAME = "agent"
USER_ID = "test_user"


def get_sessions():
    url = f"http://localhost:8000/apps/{APP_NAME}/users/{USER_ID}/sessions"

    try:
        response = httpx.get(url)
        response.raise_for_status()  # Raises an exception for 4xx/5xx errors
        sessions = response.json()
        return sessions
    except httpx.HTTPError as e:
        print(f"Error fetching sessions: {e}")
        return []
    except json.JSONDecodeError:
        print("Error parsing response JSON")
        return []


def chat(user_input: str, is_blocking: bool):
    endpoint = "/run" if is_blocking else "/run_sse"
    url = f"http://localhost:8000{endpoint}"

    payload = {
        "app_name": APP_NAME,
        "newMessage": {
            "role": "user",
            "parts": [{
                "text": user_input
            }]
        },
        "userId": USER_ID,
        "sessionId": "session_2",
        "streaming": not is_blocking
    }

    print(f"\nUser:  {user_input}")
    print("Agent: ", end="", flush=True)

    if not is_blocking:
        # --- STREAMING LOGIC ---
        with httpx.stream("POST", url, json=payload, timeout=None) as response:
            for line in response.iter_lines():
                if line.startswith("data: "):
                    data = json.loads(line[6:])

                    # Print partial model text tokens as they arrive
                    if data.get("partial"):
                        parts = data.get("content", {}).get("parts", [])
                        if parts and "text" in parts[0]:
                            print(parts[0]["text"], end="", flush=True)
        print("\n")

    else:
        # --- BLOCKING LOGIC ---
        response = httpx.post(url, json=payload, timeout=None)

        try:
            data = response.json()

            # The /run endpoint returns a list of all events in the execution graph.
            # We iterate backwards to find the final text output generated by the model.
            if isinstance(data, list):
                for event in reversed(data):
                    parts = event.get("content", {}).get("parts", [])
                    if parts and "text" in parts[0]:
                        print(parts[0]["text"])
                        break
            else:
                print("Unexpected response format:", data)

        except json.JSONDecodeError:
            print(f"Error parsing response: {response.text}")

        print("\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Chat with Jenova AI Assistant")
    parser.add_argument("prompt", type=str, help="The message to send")

    # Add an optional flag to switch to blocking mode
    parser.add_argument("--blocking",
                        action="store_true",
                        default=False,
                        help="Use blocking /run instead of streaming /run_sse")

    args = parser.parse_args()

    print("Available sessions:", get_sessions())
    chat(args.prompt, args.blocking)
