import argparse
import json

import httpx

APP_NAME = "agent"
USER_ID = "test_user"


class SessionManager:

    def __init__(self, base_url="http://localhost:8000"):
        self.base_url = base_url
        self.prefix = f"{self.base_url}/apps/{APP_NAME}/users/{USER_ID}/sessions"

    def list(self):
        return httpx.get(self.prefix).json()

    def get(self, session_id):
        return httpx.get(f"{self.prefix}/{session_id}").json()

    def create(self, session_id=None, data=None):
        # Uses POST /sessions if no ID, or POST /sessions/{id} if ID provided
        url = f"{self.prefix}/{session_id}" if session_id else self.prefix
        return httpx.post(url, json=data or {}).json()

    def update(self, session_id, data):
        return httpx.patch(f"{self.prefix}/{session_id}", json=data).json()

    def delete(self, session_id):
        return httpx.delete(f"{self.prefix}/{session_id}").json()


def chat(user_input: str, is_blocking: bool):
    endpoint = "/run" if is_blocking else "/run_sse"
    url = f"http://localhost:8000{endpoint}"

    payload = {
        "app_name": APP_NAME,
        "newMessage": {
            "role": "user",
            "parts": [{
                "text": user_input
            }]
        },
        "userId": USER_ID,
        "sessionId": "session_2",
        "streaming": not is_blocking
    }

    print(f"\nUser:  {user_input}")
    print("Agent: ", end="", flush=True)

    if not is_blocking:
        # --- STREAMING LOGIC ---
        with httpx.stream("POST", url, json=payload, timeout=None) as response:
            for line in response.iter_lines():
                if line.startswith("data: "):
                    data = json.loads(line[6:])

                    # Print partial model text tokens as they arrive
                    if data.get("partial"):
                        parts = data.get("content", {}).get("parts", [])
                        if parts and "text" in parts[0]:
                            print(parts[0]["text"], end="", flush=True)
        print("\n")

    else:
        # --- BLOCKING LOGIC ---
        response = httpx.post(url, json=payload, timeout=None)

        try:
            data = response.json()

            # The /run endpoint returns a list of all events in the execution graph.
            # We iterate backwards to find the final text output generated by the model.
            if isinstance(data, list):
                for event in reversed(data):
                    parts = event.get("content", {}).get("parts", [])
                    if parts and "text" in parts[0]:
                        print(parts[0]["text"])
                        break
            else:
                print("Unexpected response format:", data)

        except json.JSONDecodeError:
            print(f"Error parsing response: {response.text}")

        print("\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Chat with Jenova AI Assistant")

    # Adding sub-commands or flags for session management is recommended
    # to keep the CLI clean, but for now we'll integrate the manager:
    parser.add_argument("prompt",
                        type=str,
                        nargs='?',
                        help="The message to send")
    parser.add_argument("--blocking",
                        action="store_true",
                        default=False,
                        help="Use blocking /run instead of streaming /run_sse")
    parser.add_argument("--list-sessions",
                        action="store_true",
                        help="List all active sessions")

    args = parser.parse_args()

    # 1. Initialize the manager
    manager = SessionManager()

    # 2. Use the manager to list sessions if requested
    if args.list_sessions:
        print("Available sessions:", manager.list())

    # 3. Only run chat if a prompt was provided
    if args.prompt:
        chat(args.prompt, args.blocking)
    else:
        print("No prompt provided. Use --list-sessions to see sessions.")
