"""
Defines the main agent workflow graph and routing logic.
"""

from datetime import datetime
from typing import Any

from google.adk import Agent
from google.adk import Context
from google.adk import Event
from google.adk import Workflow
from google.adk.models.lite_llm import LiteLlm

from jenova.utils import create_adk_tool
from jenova.utils import discover_adk_agents
from jenova.utils import get_full_history


def process_input(node_input: str, ctx: Context) -> Event:
    """Processes the input string and provides context to the orchestrator."""
    history = get_full_history(ctx)
    current_date = datetime.now().strftime("%A, %B %d, %Y %I:%M %p")

    return Event(state={
        "input": node_input,
        "history": history,
        "system_information": current_date
    })


# DEFAULT_MODEL = "ollama_chat/devstral-small-2"
DEFAULT_MODEL = "ollama_chat/gemma4:e4b"
llm_client = LiteLlm(model=DEFAULT_MODEL)

discovered_cards = discover_adk_agents()

# 2. Build the tools
dynamic_tools: list[Any] = [create_adk_tool(card) for card in discovered_cards]

orchestrator = Agent(
    model=llm_client,
    name="orchestrator",
    instruction=
    ("You are the central orchestrator agent for the Jenova system. "
     "Your job is to analyze the user's request and delegate it to the appropriate "
     "specialized A2A agent to fulfill the request. \n\n"
     "System Information: {system_information}\n"
     "User Request: {input}\n"
     "Conversation History: {history?}\n\n"
     "Review your available tools. Determine the best expert to handle this and call them."
    ),
    tools=
    dynamic_tools  # <--- The dynamically generated ADK tools are passed here
)

# tts_formatter = Agent(
#     model=llm_client,
#     name="tts_formatter",
#     instruction=
#     ("You are a Text-To-Speech (TTS) formatting processor. "
#      "Your task is to review the most recent response generated by the assistant "
#      "and rewrite it so it is highly concise, conversational, and optimized "
#      "to be spoken out loud. \n\n"
#      "CRITICAL RULES:\n"
#      "1. Keep the response to 1-2 sentences maximum.\n"
#      "2. Strip out ALL markdown formatting, asterisks, bullet points, URLs, "
#      "and code blocks.\n"
#      "3. Spell out numbers or symbols if they need to be spoken explicitly.\n"
#      "4. Speak directly to the user in a helpful, natural voice."))

root_agent = Workflow(
    name="jenova",
    edges=[
        # ("START", process_input, orchestrator, tts_formatter),
        ("START", process_input, orchestrator),
    ],
)
